event_homepage:
    path:     /
    defaults: { _controller: EventBundle:Default:index }
event_ajoutClub:
    path:     /ajoutClub
    defaults: { _controller: EventBundle:Club:ajoutClub }
event_afficheClub:
     path:     /afficheClub
     defaults: { _controller: EventBundle:Club:afficheClub }
event_modifieClub:
     path:     /modifieClub/{id}
     defaults: { _controller: EventBundle:Club:modifieClub }
event_supprimerClub:
     path:     /supprimerClub/{id}
     defaults: { _controller: EventBundle:Club:supprimerClub }
event_ajoutEvent:
     path:     /ajoutEvent
     defaults: { _controller: EventBundle:Event:ajoutEvent }
event_afficheEvent:
     path:     /afficheEvent
     defaults: { _controller: EventBundle:Event:afficheEvent }
event_modifieEvent:
      path:     /modifieEvent/{id}
      defaults: { _controller: EventBundle:Event:modifieEvent }
event_supprimeEvent:
      path:     /supprimeEvent/{id}
      defaults: { _controller: EventBundle:Event:supprimeEvent }
event_UserEvent:
  path:     /UserEvent
  defaults: { _controller: EventBundle:Event:UserEvent }
navig:
    path:     /navig
    defaults: { _controller: EventBundle:Event:navig }









