class:
    resource: "@ClassBundle/Controller/"
    type:     annotation
    prefix:   /

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event
cours:
    resource: "@CoursBundle/Controller/"
    type:     annotation
    prefix:   /cours
vie_eleve:
    resource: "@VieEleveBundle/Resources/config/routing.yml"
    prefix:   /vie

app:
    resource: "@AppBundle/Controller"
    type: annotation

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

