# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

    email_from: 'test@gmail.com'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    ClassBundle\Controller\:
        resource: '../../src/ClassBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services

    ClassBundle\Mailer\Mailer:
        arguments:
            $mailFrom: '%email_from%'
    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
    ClassBundle\EventListener\punishmentEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    ClassBundle\EventListener\ABSNotificationSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
