<?php

namespace EventBundle\Repository;

/**
 * CategoryEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryEventRepository extends \Doctrine\ORM\EntityRepository
{
}
