<?php

namespace EventBundle\Repository;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubRepository extends \Doctrine\ORM\EntityRepository

{ public function trierEff()
{  $Query = $this->getEntityManager()->createQuery('SELECT M FROM EventBundle:Club M  ORDER BY M.effectif DESC');
    return $Query->getResult();
}

}

