<?php

namespace EventBundle\Repository;

/**
 * InscriptionClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionClubRepository extends \Doctrine\ORM\EntityRepository
{
}
