<?php

namespace ClassBundle\Repository;

/**
 * PunichmentNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PunichmentNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
