<?php

namespace CoursBundle\Repository;

/**
 * BulletinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BulletinRepository extends \Doctrine\ORM\EntityRepository
{public function remove()
{  $Query = $this->getEntityManager()->createQuery(' DELETE FROM CoursBundle:Bulletin b ');
    return $Query->getResult();}
}
