<?php

namespace CoursBundle\Repository;

/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends \Doctrine\ORM\EntityRepository
{public function tri()
{  $Query = $this->getEntityManager()->createQuery('SELECT M FROM CoursBundle:Matiere M  ORDER BY M.nomMat ');
    return $Query->getResult();
}

}
